server:
  appname: api
  appkey: passphrasewhichneedstobe32bytes!
  port: 3001
  version: 1.0.1
swagger:
  swaggerscheme: https
  swaggerprefix:
jwt:
  secret: secretkey
connection:
  primary: postgres
  replica: postgres
databases:
  - dbhost: localhost
    dbuser: postgres
    dbport: 5432
    dbpass:
    dbname: api
    dbprovider: postgresql
    dbssl: disable
    dbtz: Asia/Jakarta
    dbautomigrate: true